/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.junit.jupiter.junit.jupiter.engine)
    api(libs.org.junit.jupiter.junit.jupiter.params)
    api(project(":jmlparser-symbol-solver-core"))
    testImplementation(libs.org.hamcrest.hamcrest)
    testImplementation(libs.com.google.truth.truth)
    testImplementation(libs.org.mockito.mockito.inline)
}

description = "io.github.jmltoolkit:jmlparser-symbol-solver-testing"
