// This file is part of KeY - Integrated Deductive Software Design 
//
// Copyright (C) 2001-2011 Universitaet Karlsruhe (TH), Germany 
//                         Universitaet Koblenz-Landau, Germany
//                         Chalmers University of Technology, Sweden
// Copyright (C) 2011-2013 Karlsruhe Institute of Technology, Germany 
//                         Technical University Darmstadt, Germany
//                         Chalmers University of Technology, Sweden
//
// The KeY system is protected by the GNU General 
// Public License. See LICENSE.TXT for details.
// 

/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed May 14 11:55:38 CEST 2008
 */
package javax.swing;

public abstract class AbstractButton extends javax.swing.JComponent implements java.awt.ItemSelectable, javax.swing.SwingConstants
{
   public final static java.lang.String MODEL_CHANGED_PROPERTY = "model";
   public final static java.lang.String TEXT_CHANGED_PROPERTY = "text";
   public final static java.lang.String MNEMONIC_CHANGED_PROPERTY = "mnemonic";
   public final static java.lang.String MARGIN_CHANGED_PROPERTY = "margin";
   public final static java.lang.String VERTICAL_ALIGNMENT_CHANGED_PROPERTY = "verticalAlignment";
   public final static java.lang.String HORIZONTAL_ALIGNMENT_CHANGED_PROPERTY = "horizontalAlignment";
   public final static java.lang.String VERTICAL_TEXT_POSITION_CHANGED_PROPERTY = "verticalTextPosition";
   public final static java.lang.String HORIZONTAL_TEXT_POSITION_CHANGED_PROPERTY = "horizontalTextPosition";
   public final static java.lang.String BORDER_PAINTED_CHANGED_PROPERTY = "borderPainted";
   public final static java.lang.String FOCUS_PAINTED_CHANGED_PROPERTY = "focusPainted";
   public final static java.lang.String ROLLOVER_ENABLED_CHANGED_PROPERTY = "rolloverEnabled";
   public final static java.lang.String CONTENT_AREA_FILLED_CHANGED_PROPERTY = "contentAreaFilled";
   public final static java.lang.String ICON_CHANGED_PROPERTY = "icon";
   public final static java.lang.String PRESSED_ICON_CHANGED_PROPERTY = "pressedIcon";
   public final static java.lang.String SELECTED_ICON_CHANGED_PROPERTY = "selectedIcon";
   public final static java.lang.String ROLLOVER_ICON_CHANGED_PROPERTY = "rolloverIcon";
   public final static java.lang.String ROLLOVER_SELECTED_ICON_CHANGED_PROPERTY = "rolloverSelectedIcon";
   public final static java.lang.String DISABLED_ICON_CHANGED_PROPERTY = "disabledIcon";
   public final static java.lang.String DISABLED_SELECTED_ICON_CHANGED_PROPERTY = "disabledSelectedIcon";
   //protected javax.swing.ButtonModel model;
   protected javax.swing.event.ChangeListener changeListener;
   protected java.awt.event.ActionListener actionListener;
   protected java.awt.event.ItemListener itemListener;
   protected javax.swing.event.ChangeEvent changeEvent;

   public AbstractButton();
   public void setHideActionText(boolean arg0);
   public boolean getHideActionText();
   public java.lang.String getText();
   public void setText(java.lang.String arg0);
   public boolean isSelected();
   public void setSelected(boolean arg0);
   public void doClick();
   public void doClick(int arg0);
   public void setMargin(java.awt.Insets arg0);
   public java.awt.Insets getMargin();
   public javax.swing.Icon getIcon();
   public void setIcon(javax.swing.Icon arg0);
   public javax.swing.Icon getPressedIcon();
   public void setPressedIcon(javax.swing.Icon arg0);
   public javax.swing.Icon getSelectedIcon();
   public void setSelectedIcon(javax.swing.Icon arg0);
   public javax.swing.Icon getRolloverIcon();
   public void setRolloverIcon(javax.swing.Icon arg0);
   public javax.swing.Icon getRolloverSelectedIcon();
   public void setRolloverSelectedIcon(javax.swing.Icon arg0);
   public javax.swing.Icon getDisabledIcon();
   public void setDisabledIcon(javax.swing.Icon arg0);
   public javax.swing.Icon getDisabledSelectedIcon();
   public void setDisabledSelectedIcon(javax.swing.Icon arg0);
   public int getVerticalAlignment();
   public void setVerticalAlignment(int arg0);
   public int getHorizontalAlignment();
   public void setHorizontalAlignment(int arg0);
   public int getVerticalTextPosition();
   public void setVerticalTextPosition(int arg0);
   public int getHorizontalTextPosition();
   public void setHorizontalTextPosition(int arg0);
   public int getIconTextGap();
   public void setIconTextGap(int arg0);
   protected int checkHorizontalKey(int arg0, java.lang.String arg1);
   protected int checkVerticalKey(int arg0, java.lang.String arg1);
   public void removeNotify();
   public void setActionCommand(java.lang.String arg0);
   public java.lang.String getActionCommand();
   public void setAction(javax.swing.Action arg0);
   public javax.swing.Action getAction();
   protected void configurePropertiesFromAction(javax.swing.Action arg0);
   protected void actionPropertyChanged(javax.swing.Action arg0, java.lang.String arg1);
   protected java.beans.PropertyChangeListener createActionPropertyChangeListener(javax.swing.Action arg0);
   public boolean isBorderPainted();
   public void setBorderPainted(boolean arg0);
   protected void paintBorder(java.awt.Graphics arg0);
   public boolean isFocusPainted();
   public void setFocusPainted(boolean arg0);
   public boolean isContentAreaFilled();
   public void setContentAreaFilled(boolean arg0);
   public boolean isRolloverEnabled();
   public void setRolloverEnabled(boolean arg0);
   public int getMnemonic();
   public void setMnemonic(int arg0);
   public void setMnemonic(char arg0);
   public void setDisplayedMnemonicIndex(int arg0) throws java.lang.IllegalArgumentException;
   public int getDisplayedMnemonicIndex();
   public void setMultiClickThreshhold(long arg0);
   public long getMultiClickThreshhold();
   public javax.swing.ButtonModel getModel();
   public void setModel(javax.swing.ButtonModel arg0);
   public javax.swing.plaf.ButtonUI getUI();
   public void setUI(javax.swing.plaf.ButtonUI arg0);
   public void updateUI();
   protected void addImpl(java.awt.Component arg0, java.lang.Object arg1, int arg2);
   public void setLayout(java.awt.LayoutManager arg0);
   public void addChangeListener(javax.swing.event.ChangeListener arg0);
   public void removeChangeListener(javax.swing.event.ChangeListener arg0);
   public javax.swing.event.ChangeListener[] getChangeListeners();
   protected void fireStateChanged();
   public void addActionListener(java.awt.event.ActionListener arg0);
   public void removeActionListener(java.awt.event.ActionListener arg0);
   public java.awt.event.ActionListener[] getActionListeners();
   protected javax.swing.event.ChangeListener createChangeListener();
   protected void fireActionPerformed(java.awt.event.ActionEvent arg0);
   protected void fireItemStateChanged(java.awt.event.ItemEvent arg0);
   protected java.awt.event.ActionListener createActionListener();
   protected java.awt.event.ItemListener createItemListener();
   public void setEnabled(boolean arg0);
   public java.lang.String getLabel();
   public void setLabel(java.lang.String arg0);
   public void addItemListener(java.awt.event.ItemListener arg0);
   public void removeItemListener(java.awt.event.ItemListener arg0);
   public java.awt.event.ItemListener[] getItemListeners();
   public java.lang.Object[] getSelectedObjects();
   protected void init(java.lang.String arg0, javax.swing.Icon arg1);
   public boolean imageUpdate(java.awt.Image arg0, int arg1, int arg2, int arg3, int arg4, int arg5);
   protected java.lang.String paramString();
}
