// This file is part of KeY - Integrated Deductive Software Design 
//
// Copyright (C) 2001-2011 Universitaet Karlsruhe (TH), Germany 
//                         Universitaet Koblenz-Landau, Germany
//                         Chalmers University of Technology, Sweden
// Copyright (C) 2011-2013 Karlsruhe Institute of Technology, Germany 
//                         Technical University Darmstadt, Germany
//                         Chalmers University of Technology, Sweden
//
// The KeY system is protected by the GNU General 
// Public License. See LICENSE.TXT for details.
// 

/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed May 14 11:55:38 CEST 2008
 */
package javax.swing;

public class JButton extends javax.swing.AbstractButton implements javax.accessibility.Accessible
{

   public JButton();
   public JButton(javax.swing.Icon arg0);
   public JButton(java.lang.String arg0);
   public JButton(javax.swing.Action arg0);
   public JButton(java.lang.String arg0, javax.swing.Icon arg1);
   public void updateUI();
   public java.lang.String getUIClassID();
   public boolean isDefaultButton();
   public boolean isDefaultCapable();
   public void setDefaultCapable(boolean arg0);
   public void removeNotify();
   protected java.lang.String paramString();
   public javax.accessibility.AccessibleContext getAccessibleContext();
}
