// This file is part of KeY - Integrated Deductive Software Design 
//
// Copyright (C) 2001-2011 Universitaet Karlsruhe (TH), Germany 
//                         Universitaet Koblenz-Landau, Germany
//                         Chalmers University of Technology, Sweden
// Copyright (C) 2011-2013 Karlsruhe Institute of Technology, Germany 
//                         Technical University Darmstadt, Germany
//                         Chalmers University of Technology, Sweden
//
// The KeY system is protected by the GNU General 
// Public License. See LICENSE.TXT for details.
// 

/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed May 14 11:54:58 CEST 2008
 */
package javax.swing;

public class JOptionPane extends javax.swing.JComponent implements javax.accessibility.Accessible
{
   public final static java.lang.Object UNINITIALIZED_VALUE;
   public final static int DEFAULT_OPTION = -1;
   public final static int YES_NO_OPTION = 0;
   public final static int YES_NO_CANCEL_OPTION = 1;
   public final static int OK_CANCEL_OPTION = 2;
   public final static int YES_OPTION = 0;
   public final static int NO_OPTION = 1;
   public final static int CANCEL_OPTION = 2;
   public final static int OK_OPTION = 0;
   public final static int CLOSED_OPTION = -1;
   public final static int ERROR_MESSAGE = 0;
   public final static int INFORMATION_MESSAGE = 1;
   public final static int WARNING_MESSAGE = 2;
   public final static int QUESTION_MESSAGE = 3;
   public final static int PLAIN_MESSAGE = -1;
   public final static java.lang.String ICON_PROPERTY = "icon";
   public final static java.lang.String MESSAGE_PROPERTY = "message";
   public final static java.lang.String VALUE_PROPERTY = "value";
   public final static java.lang.String OPTIONS_PROPERTY = "options";
   public final static java.lang.String INITIAL_VALUE_PROPERTY = "initialValue";
   public final static java.lang.String MESSAGE_TYPE_PROPERTY = "messageType";
   public final static java.lang.String OPTION_TYPE_PROPERTY = "optionType";
   public final static java.lang.String SELECTION_VALUES_PROPERTY = "selectionValues";
   public final static java.lang.String INITIAL_SELECTION_VALUE_PROPERTY = "initialSelectionValue";
   public final static java.lang.String INPUT_VALUE_PROPERTY = "inputValue";
   public final static java.lang.String WANTS_INPUT_PROPERTY = "wantsInput";
   protected javax.swing.Icon icon;
   protected java.lang.Object message;
   protected java.lang.Object[] options;
   protected java.lang.Object initialValue;
   protected int messageType;
   protected int optionType;
   protected java.lang.Object value;
   protected java.lang.Object[] selectionValues;
   protected java.lang.Object inputValue;
   protected java.lang.Object initialSelectionValue;
   protected boolean wantsInput;

   public static java.lang.String showInputDialog(java.lang.Object arg0) throws java.awt.HeadlessException;
   public static java.lang.String showInputDialog(java.lang.Object arg0, java.lang.Object arg1);
   public static java.lang.String showInputDialog(java.awt.Component arg0, java.lang.Object arg1) throws java.awt.HeadlessException;
   public static java.lang.String showInputDialog(java.awt.Component arg0, java.lang.Object arg1, java.lang.Object arg2);
   public static java.lang.String showInputDialog(java.awt.Component arg0, java.lang.Object arg1, java.lang.String arg2, int arg3) throws java.awt.HeadlessException;
   public static java.lang.Object showInputDialog(java.awt.Component arg0, java.lang.Object arg1, java.lang.String arg2, int arg3, javax.swing.Icon arg4, java.lang.Object[] arg5, java.lang.Object arg6) throws java.awt.HeadlessException;
   public static void showMessageDialog(java.awt.Component arg0, java.lang.Object arg1) throws java.awt.HeadlessException;
   public static void showMessageDialog(java.awt.Component arg0, java.lang.Object arg1, java.lang.String arg2, int arg3) throws java.awt.HeadlessException;
   public static void showMessageDialog(java.awt.Component arg0, java.lang.Object arg1, java.lang.String arg2, int arg3, javax.swing.Icon arg4) throws java.awt.HeadlessException;
   public static int showConfirmDialog(java.awt.Component arg0, java.lang.Object arg1) throws java.awt.HeadlessException;
   public static int showConfirmDialog(java.awt.Component arg0, java.lang.Object arg1, java.lang.String arg2, int arg3) throws java.awt.HeadlessException;
   public static int showConfirmDialog(java.awt.Component arg0, java.lang.Object arg1, java.lang.String arg2, int arg3, int arg4) throws java.awt.HeadlessException;
   public static int showConfirmDialog(java.awt.Component arg0, java.lang.Object arg1, java.lang.String arg2, int arg3, int arg4, javax.swing.Icon arg5) throws java.awt.HeadlessException;
   public static int showOptionDialog(java.awt.Component arg0, java.lang.Object arg1, java.lang.String arg2, int arg3, int arg4, javax.swing.Icon arg5, java.lang.Object[] arg6, java.lang.Object arg7) throws java.awt.HeadlessException;
   public javax.swing.JDialog createDialog(java.awt.Component arg0, java.lang.String arg1) throws java.awt.HeadlessException;
   public javax.swing.JDialog createDialog(java.lang.String arg0) throws java.awt.HeadlessException;
   public static void showInternalMessageDialog(java.awt.Component arg0, java.lang.Object arg1);
   public static void showInternalMessageDialog(java.awt.Component arg0, java.lang.Object arg1, java.lang.String arg2, int arg3);
   public static void showInternalMessageDialog(java.awt.Component arg0, java.lang.Object arg1, java.lang.String arg2, int arg3, javax.swing.Icon arg4);
   public static int showInternalConfirmDialog(java.awt.Component arg0, java.lang.Object arg1);
   public static int showInternalConfirmDialog(java.awt.Component arg0, java.lang.Object arg1, java.lang.String arg2, int arg3);
   public static int showInternalConfirmDialog(java.awt.Component arg0, java.lang.Object arg1, java.lang.String arg2, int arg3, int arg4);
   public static int showInternalConfirmDialog(java.awt.Component arg0, java.lang.Object arg1, java.lang.String arg2, int arg3, int arg4, javax.swing.Icon arg5);
   public static int showInternalOptionDialog(java.awt.Component arg0, java.lang.Object arg1, java.lang.String arg2, int arg3, int arg4, javax.swing.Icon arg5, java.lang.Object[] arg6, java.lang.Object arg7);
   public static java.lang.String showInternalInputDialog(java.awt.Component arg0, java.lang.Object arg1);
   public static java.lang.String showInternalInputDialog(java.awt.Component arg0, java.lang.Object arg1, java.lang.String arg2, int arg3);
   public static java.lang.Object showInternalInputDialog(java.awt.Component arg0, java.lang.Object arg1, java.lang.String arg2, int arg3, javax.swing.Icon arg4, java.lang.Object[] arg5, java.lang.Object arg6);
   public javax.swing.JInternalFrame createInternalFrame(java.awt.Component arg0, java.lang.String arg1);
   public static java.awt.Frame getFrameForComponent(java.awt.Component arg0) throws java.awt.HeadlessException;
   public static javax.swing.JDesktopPane getDesktopPaneForComponent(java.awt.Component arg0);
   public static void setRootFrame(java.awt.Frame arg0);
   public static java.awt.Frame getRootFrame() throws java.awt.HeadlessException;
   public JOptionPane();
   public JOptionPane(java.lang.Object arg0);
   public JOptionPane(java.lang.Object arg0, int arg1);
   public JOptionPane(java.lang.Object arg0, int arg1, int arg2);
   public JOptionPane(java.lang.Object arg0, int arg1, int arg2, javax.swing.Icon arg3);
   public JOptionPane(java.lang.Object arg0, int arg1, int arg2, javax.swing.Icon arg3, java.lang.Object[] arg4);
   public JOptionPane(java.lang.Object arg0, int arg1, int arg2, javax.swing.Icon arg3, java.lang.Object[] arg4, java.lang.Object arg5);
   public void setUI(javax.swing.plaf.OptionPaneUI arg0);
   public javax.swing.plaf.OptionPaneUI getUI();
   public void updateUI();
   public java.lang.String getUIClassID();
   public void setMessage(java.lang.Object arg0);
   public java.lang.Object getMessage();
   public void setIcon(javax.swing.Icon arg0);
   public javax.swing.Icon getIcon();
   public void setValue(java.lang.Object arg0);
   public java.lang.Object getValue();
   public void setOptions(java.lang.Object[] arg0);
   public java.lang.Object[] getOptions();
   public void setInitialValue(java.lang.Object arg0);
   public java.lang.Object getInitialValue();
   public void setMessageType(int arg0);
   public int getMessageType();
   public void setOptionType(int arg0);
   public int getOptionType();
   public void setSelectionValues(java.lang.Object[] arg0);
   public java.lang.Object[] getSelectionValues();
   public void setInitialSelectionValue(java.lang.Object arg0);
   public java.lang.Object getInitialSelectionValue();
   public void setInputValue(java.lang.Object arg0);
   public java.lang.Object getInputValue();
   public int getMaxCharactersPerLineCount();
   public void setWantsInput(boolean arg0);
   public boolean getWantsInput();
   public void selectInitialValue();
   protected java.lang.String paramString();
   public javax.accessibility.AccessibleContext getAccessibleContext();
}
