// This file is part of KeY - Integrated Deductive Software Design 
//
// Copyright (C) 2001-2011 Universitaet Karlsruhe (TH), Germany 
//                         Universitaet Koblenz-Landau, Germany
//                         Chalmers University of Technology, Sweden
// Copyright (C) 2011-2013 Karlsruhe Institute of Technology, Germany 
//                         Technical University Darmstadt, Germany
//                         Chalmers University of Technology, Sweden
//
// The KeY system is protected by the GNU General 
// Public License. See LICENSE.TXT for details.
// 

/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed May 14 11:55:36 CEST 2008
 */
package javax.swing;

public class JToggleButton extends javax.swing.AbstractButton implements javax.accessibility.Accessible
{

   public JToggleButton();
   public JToggleButton(javax.swing.Icon arg0);
   public JToggleButton(javax.swing.Icon arg0, boolean arg1);
   public JToggleButton(java.lang.String arg0);
   public JToggleButton(java.lang.String arg0, boolean arg1);
   public JToggleButton(javax.swing.Action arg0);
   public JToggleButton(java.lang.String arg0, javax.swing.Icon arg1);
   public JToggleButton(java.lang.String arg0, javax.swing.Icon arg1, boolean arg2);
   public void updateUI();
   public java.lang.String getUIClassID();
   protected java.lang.String paramString();
   public javax.accessibility.AccessibleContext getAccessibleContext();
}
