package gui;

/* Generated by Together */

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class Start {
        public static void main(String[] argv) {
                IssueCardUI gui = new IssueCardUI ();
                gui.initGUI();
        }
}

