version: '{build}'
os: Windows Server 2012

environment:
  appveyor_build_worker_cloud: gce

init:
  # Setup autocrlf -- by default, appveyor uses autocrlf input
  # ... This affects tests which expect resource files to have the systems's line separator.
  - git config --global core.autocrlf true

install:
  # Download maven
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://www.us.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  # Setup environment variables for Maven and Java
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk10
  - cmd: SET M2_HOME=C:\maven\apache-maven-3.6.3
  - cmd: SET MAVEN_OPTS=-Xmx1g
  - cmd: SET JAVA_OPTS=-Xmx1g
  - cmd: SET PATH=C:\maven\apache-maven-3.6.3\bin;%JAVA_HOME%\bin;%PATH%
  # Output the git config re: autocrlf to verify the "current" setting
  - cmd: git config core.autocrlf

# Appveyor is used for testing only -- the build script is not required.
build_script:
  - echo ignore this

test_script:
  - mvn -B clean install --batch-mode

# Use of the cache speeds up future tests, meaning that dependencies do not need to be re-downloaded on every run.
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
