package com.github.javaparser.ast.observing;

/**
 * Properties considered by the AstObserver
 */
public enum ObservableProperty {
    RANGE, DEFAULT_VALUE, NAME, MODIFIERS, TYPE, ANNOTATIONS, EXTENDS, IMPLEMENTS_LIST, TYPE_PARAMETERS, INTERFACE, PARAMETERS, THROWS, ARGS, CLASS_BODY, ENTRIES, VARIABLES, ELEMENT_TYPE, STATIC, BLOCK, BODY, ARRAY_BRACKET_PAIRS_AFTER_TYPE, VAR_ARGS, ID, MEMBERS, INIT, ARRAY_BRACKET_PAIRS_AFTER_ID, CONTENT, COMMENTED_NODE, INDEX, INITIALIZER, LEVELS, VALUES, TARGET, VALUE, LEFT, OPERATOR, RIGHT, EXPR, CONDITION, ELSE_EXPR, THEN_EXPR, INNER, FIELD, SCOPE, TYPE_ARGUMENTS, PARAMETERS_ENCLOSED, IDENTIFIER, QUALIFIER, PAIRS, ANONYMOUS_CLASS_BODY, MEMBER_VALUE, CLASS_EXPR, STATIC_MEMBER, CHECK, MSG, STMTS, CATCH_BLOCK, PARAM, IS_THIS, ITERABLE, VARIABLE, COMPARE, UPDATE, ELSE_STMT, THEN_STMT, LABEL, STMT, SELECTOR, CATCHS, FINALLY_BLOCK, TRY_BLOCK, RESOURCES, TYPE_DECLARATION, COMPONENT_TYPE, ELEMENTS, SUPER, PACKAGE, IMPORTS, TYPES, TYPE_BOUND, DIMENSION, COMMENT
}
