// This file is part of KeY - Integrated Deductive Software Design 
//
// Copyright (C) 2001-2011 Universitaet Karlsruhe (TH), Germany 
//                         Universitaet Koblenz-Landau, Germany
//                         Chalmers University of Technology, Sweden
// Copyright (C) 2011-2013 Karlsruhe Institute of Technology, Germany 
//                         Technical University Darmstadt, Germany
//                         Chalmers University of Technology, Sweden
//
// The KeY system is protected by the GNU General 
// Public License. See LICENSE.TXT for details.
// 

/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Tue Apr 15 10:18:17 CEST 2008
 */
package java.lang;

public class IllegalStateException extends java.lang.RuntimeException
{

   public IllegalStateException();
   public IllegalStateException(java.lang.String arg0);
   public IllegalStateException(java.lang.String arg0, java.lang.Throwable arg1);
   public IllegalStateException(java.lang.Throwable arg0);
}
