// This file is part of KeY - Integrated Deductive Software Design 
//
// Copyright (C) 2001-2011 Universitaet Karlsruhe (TH), Germany 
//                         Universitaet Koblenz-Landau, Germany
//                         Chalmers University of Technology, Sweden
// Copyright (C) 2011-2013 Karlsruhe Institute of Technology, Germany 
//                         Technical University Darmstadt, Germany
//                         Chalmers University of Technology, Sweden
//
// The KeY system is protected by the GNU General 
// Public License. See LICENSE.TXT for details.
// 

/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Tue Apr 15 10:18:20 CEST 2008
 */
package java.io;

public abstract class InputStream extends java.lang.Object implements java.io.Closeable
{

   public InputStream();
   public abstract int read() throws java.io.IOException;
   public int read(byte[] arg0) throws java.io.IOException;
   public int read(byte[] arg0, int arg1, int arg2) throws java.io.IOException;
   public long skip(long arg0) throws java.io.IOException;
   public int available() throws java.io.IOException;
   public void close() throws java.io.IOException;
   public void mark(int arg0);
   public void reset() throws java.io.IOException;
   public boolean markSupported();
}
