/*
 * Test data strategy for package .
 *
 * Generated by JMLUnitNG 1.4b1 (104), 2013-10-08 22:59 -0700.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */
import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import org.jmlspecs.jmlunitng.strategy.IntStrategy;

/**
 * Test data strategy for package <default>. Provides
 * package-scope test values for type int.
 * 
 * @author JMLUnitNG 1.4b1 (104)
 * @version 2013-10-08 22:59 -0700
 */
public class PackageStrategy_int 
  extends IntStrategy {
  /**
   * @return package-scope values for type int.
   */
  public RepeatedAccessIterator<?> packageValues() {
    return new ObjectArrayIterator<Object>
    (new Object[] 
     { /* add package-scope int values or generators here */ });
  }
}
