@startuml
class java.Class {
}

class java.Method {}

class jml.Expression {}
class jml.Formula {}
class jml.Method {
  + visibility : VisibilityModifier
  + kind : {GHOST, MODEL}
  + name : String}
  + params : List<Parameters>
  + body : jml.BlockStmt
}

class jml.Field {
  + visibility : VisibilityModifier
  + kind : {GHOST, MODEL}
  + name : String
  + params : List<Parameters>
}


class jml.Class {
  +\inv : Formula
  +\initially : Formula
}

class jml.Contract {
  + name : String
  + assignable : Expression
}

jml.Contract -- "1..*" jml.FClause : +requires
jml.Contract -- "1..*" jml.FClause : +ensures
jml.Contract -- "1..*" jml.EClause : +diverges
jml.Contract -- "1..*" jml.EClause : +assignable

class jml.FClause {}
class jml.EClause {}

jml.EClause o-- "1..*" jml.Expression

java.Class --> "0..*" jml.Field
jml.FClause --> jml.Formula :  +/all
jml.FClause o-- "1..*" jml.Formula
java.Class --> jml.Class
java.Class --> "0..*" jml.Method
java.Method --> "0..*" jml.Contract
jml.Field --> "0..1" jml.Expression : "representsBy"
@enduml