/*
 * Test data strategy for Add.
 *
 * Generated by JMLUnitNG 1.4b1 (104), 2013-10-08 22:59 -0700.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;

/**
 * Test data strategy for Add. Provides
 * test values for parameter "int the_x" 
 * of method "Add(int, int)". 
 * 
 * @author JMLUnitNG 1.4b1 (104)
 * @version 2013-10-08 22:59 -0700
 */
public class Add_Add__int_the_x__int_the_y__0__the_x
  extends Add_ClassStrategy_int {
  /**
   * @return local-scope values for parameter 
   *  "int the_x".
   */
  public RepeatedAccessIterator<?> localValues() {
  	return new ObjectArrayIterator<Object>
  	(new Object[]
  	 { /* add local-scope int values or generators here */ });
  }
}
