/*
 * Test data strategy for Add.
 *
 * Generated by JMLUnitNG 1.4b1 (104), 2013-10-08 22:59 -0700.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */
import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;

/**
 * Test data strategy for Add. Provides
 * class-scope test values for type int.
 * 
 * @author JMLUnitNG 1.4b1 (104)
 * @version 2013-10-08 22:59 -0700
 */
public class Add_ClassStrategy_int 
  extends PackageStrategy_int {
  /**
   * @return class-scope values for type int.
   */
  public RepeatedAccessIterator<?> classValues() {
    return new ObjectArrayIterator<Object>
    (new Object[] 
  	 { /* add class-scope int values or generators here */ });
  }
}
