/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":jmlparser-core"))
    api(libs.org.junit.jupiter.junit.jupiter.engine)
    api(libs.org.junit.vintage.junit.vintage.engine)
    testImplementation(libs.org.jbehave.jbehave.core)
    testImplementation(libs.org.hamcrest.hamcrest)
}

description = "io.github.jmltoolkit:jmlparser-core-testing-bdd"
