/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":jmlparser-core"))
    testImplementation(libs.bundles.testing)
    testRuntimeOnly(libs.bundles.testing.runtime)
    testImplementation(libs.com.squareup.okhttp3.okhttp)
    testImplementation(libs.com.squareup.okhttp3.okhttp.jvm)
}

description = "io.github.jmltoolkit:jmlparser-core-testing"
