/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":jmlparser-core"))
    api(libs.org.javassist.javassist)
    api(libs.com.google.guava.guava)
    api(libs.org.checkerframework.checker.qual)
}

description = "io.github.jmltoolkit:jmlparser-symbol-solver-core"
