/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":jmlparser-core"))
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
}

description = "io.github.jmltoolkit:jmlparser-core-generators"
