/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.junit.jupiter.junit.jupiter.engine)
    api(project(":jmlparser-core"))
    api(libs.jakarta.json.jakarta.json.api)
    testImplementation(libs.org.eclipse.parsson.parsson)
}

description = "io.github.jmltoolkit:jmlparser-core-serialization"
