// This file is part of KeY - Integrated Deductive Software Design 
//
// Copyright (C) 2001-2011 Universitaet Karlsruhe (TH), Germany 
//                         Universitaet Koblenz-Landau, Germany
//                         Chalmers University of Technology, Sweden
// Copyright (C) 2011-2013 Karlsruhe Institute of Technology, Germany 
//                         Technical University Darmstadt, Germany
//                         Chalmers University of Technology, Sweden
//
// The KeY system is protected by the GNU General 
// Public License. See LICENSE.TXT for details.
// 

/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed May 14 11:55:33 CEST 2008
 */
package javax.swing;

public class BorderFactory extends java.lang.Object
{

   public static javax.swing.border.Border createLineBorder(java.awt.Color arg0);
   public static javax.swing.border.Border createLineBorder(java.awt.Color arg0, int arg1);
   public static javax.swing.border.Border createRaisedBevelBorder();
   public static javax.swing.border.Border createLoweredBevelBorder();
   public static javax.swing.border.Border createBevelBorder(int arg0);
   public static javax.swing.border.Border createBevelBorder(int arg0, java.awt.Color arg1, java.awt.Color arg2);
   public static javax.swing.border.Border createBevelBorder(int arg0, java.awt.Color arg1, java.awt.Color arg2, java.awt.Color arg3, java.awt.Color arg4);
   public static javax.swing.border.Border createEtchedBorder();
   public static javax.swing.border.Border createEtchedBorder(java.awt.Color arg0, java.awt.Color arg1);
   public static javax.swing.border.Border createEtchedBorder(int arg0);
   public static javax.swing.border.Border createEtchedBorder(int arg0, java.awt.Color arg1, java.awt.Color arg2);
   public static javax.swing.border.TitledBorder createTitledBorder(java.lang.String arg0);
   public static javax.swing.border.TitledBorder createTitledBorder(javax.swing.border.Border arg0);
   public static javax.swing.border.TitledBorder createTitledBorder(javax.swing.border.Border arg0, java.lang.String arg1);
   public static javax.swing.border.TitledBorder createTitledBorder(javax.swing.border.Border arg0, java.lang.String arg1, int arg2, int arg3);
   public static javax.swing.border.TitledBorder createTitledBorder(javax.swing.border.Border arg0, java.lang.String arg1, int arg2, int arg3, java.awt.Font arg4);
   public static javax.swing.border.TitledBorder createTitledBorder(javax.swing.border.Border arg0, java.lang.String arg1, int arg2, int arg3, java.awt.Font arg4, java.awt.Color arg5);
   public static javax.swing.border.Border createEmptyBorder();
   public static javax.swing.border.Border createEmptyBorder(int arg0, int arg1, int arg2, int arg3);
   public static javax.swing.border.CompoundBorder createCompoundBorder();
   public static javax.swing.border.CompoundBorder createCompoundBorder(javax.swing.border.Border arg0, javax.swing.border.Border arg1);
   public static javax.swing.border.MatteBorder createMatteBorder(int arg0, int arg1, int arg2, int arg3, java.awt.Color arg4);
   public static javax.swing.border.MatteBorder createMatteBorder(int arg0, int arg1, int arg2, int arg3, javax.swing.Icon arg4);
}
