// This file is part of KeY - Integrated Deductive Software Design 
//
// Copyright (C) 2001-2011 Universitaet Karlsruhe (TH), Germany 
//                         Universitaet Koblenz-Landau, Germany
//                         Chalmers University of Technology, Sweden
// Copyright (C) 2011-2013 Karlsruhe Institute of Technology, Germany 
//                         Technical University Darmstadt, Germany
//                         Chalmers University of Technology, Sweden
//
// The KeY system is protected by the GNU General 
// Public License. See LICENSE.TXT for details.
// 

/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed May 14 11:55:45 CEST 2008
 */
package java.awt;

public class Dimension extends java.awt.geom.Dimension2D implements java.io.Serializable
{
   public int width;
   public int height;

   public Dimension();
   public Dimension(java.awt.Dimension arg0);
   public Dimension(int arg0, int arg1);
   public double getWidth();
   public double getHeight();
   public void setSize(double arg0, double arg1);
   public java.awt.Dimension getSize();
   public void setSize(java.awt.Dimension arg0);
   public void setSize(int arg0, int arg1);
   public boolean equals(java.lang.Object arg0);
   public int hashCode();
   public java.lang.String toString();
}
