// This file is part of KeY - Integrated Deductive Software Design 
//
// Copyright (C) 2001-2011 Universitaet Karlsruhe (TH), Germany 
//                         Universitaet Koblenz-Landau, Germany
//                         Chalmers University of Technology, Sweden
// Copyright (C) 2011-2013 Karlsruhe Institute of Technology, Germany 
//                         Technical University Darmstadt, Germany
//                         Chalmers University of Technology, Sweden
//
// The KeY system is protected by the GNU General 
// Public License. See LICENSE.TXT for details.
// 

/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed May 14 11:55:45 CEST 2008
 */
package java.awt;

public class Frame extends java.awt.Window implements java.awt.MenuContainer
{
   public final static int DEFAULT_CURSOR = 0;
   public final static int CROSSHAIR_CURSOR = 1;
   public final static int TEXT_CURSOR = 2;
   public final static int WAIT_CURSOR = 3;
   public final static int SW_RESIZE_CURSOR = 4;
   public final static int SE_RESIZE_CURSOR = 5;
   public final static int NW_RESIZE_CURSOR = 6;
   public final static int NE_RESIZE_CURSOR = 7;
   public final static int N_RESIZE_CURSOR = 8;
   public final static int S_RESIZE_CURSOR = 9;
   public final static int W_RESIZE_CURSOR = 10;
   public final static int E_RESIZE_CURSOR = 11;
   public final static int HAND_CURSOR = 12;
   public final static int MOVE_CURSOR = 13;
   public final static int NORMAL = 0;
   public final static int ICONIFIED = 1;
   public final static int MAXIMIZED_HORIZ = 2;
   public final static int MAXIMIZED_VERT = 4;
   public final static int MAXIMIZED_BOTH = 6;

   public Frame() throws java.awt.HeadlessException;
   public Frame(java.awt.GraphicsConfiguration arg0);
   public Frame(java.lang.String arg0) throws java.awt.HeadlessException;
   public Frame(java.lang.String arg0, java.awt.GraphicsConfiguration arg1);
   public void addNotify();
   public java.lang.String getTitle();
   public void setTitle(java.lang.String arg0);
   public java.awt.Image getIconImage();
   public void setIconImage(java.awt.Image arg0);
   public java.awt.MenuBar getMenuBar();
   public void setMenuBar(java.awt.MenuBar arg0);
   public boolean isResizable();
   public void setResizable(boolean arg0);
   public void setState(int arg0);
   public void setExtendedState(int arg0);
   public int getState();
   public int getExtendedState();
   public void setMaximizedBounds(java.awt.Rectangle arg0);
   public java.awt.Rectangle getMaximizedBounds();
   public void setUndecorated(boolean arg0);
   public boolean isUndecorated();
   public void remove(java.awt.MenuComponent arg0);
   public void removeNotify();
   protected java.lang.String paramString();
   public void setCursor(int arg0);
   public int getCursorType();
   public static java.awt.Frame[] getFrames();
   public javax.accessibility.AccessibleContext getAccessibleContext();
}
