// This file is part of KeY - Integrated Deductive Software Design 
//
// Copyright (C) 2001-2011 Universitaet Karlsruhe (TH), Germany 
//                         Universitaet Koblenz-Landau, Germany
//                         Chalmers University of Technology, Sweden
// Copyright (C) 2011-2013 Karlsruhe Institute of Technology, Germany 
//                         Technical University Darmstadt, Germany
//                         Chalmers University of Technology, Sweden
//
// The KeY system is protected by the GNU General 
// Public License. See LICENSE.TXT for details.
// 

/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed May 14 11:55:40 CEST 2008
 */
package javax.swing;

public class JPanel extends javax.swing.JComponent implements javax.accessibility.Accessible
{

   public JPanel(java.awt.LayoutManager arg0, boolean arg1);
   public JPanel(java.awt.LayoutManager arg0);
   public JPanel(boolean arg0);
   public JPanel();
   public void updateUI();
   public javax.swing.plaf.PanelUI getUI();
   public void setUI(javax.swing.plaf.PanelUI arg0);
   public java.lang.String getUIClassID();
   protected java.lang.String paramString();
   public javax.accessibility.AccessibleContext getAccessibleContext();
}
