// This file is part of KeY - Integrated Deductive Software Design 
//
// Copyright (C) 2001-2011 Universitaet Karlsruhe (TH), Germany 
//                         Universitaet Koblenz-Landau, Germany
//                         Chalmers University of Technology, Sweden
// Copyright (C) 2011-2013 Karlsruhe Institute of Technology, Germany 
//                         Technical University Darmstadt, Germany
//                         Chalmers University of Technology, Sweden
//
// The KeY system is protected by the GNU General 
// Public License. See LICENSE.TXT for details.
// 

/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed May 14 11:55:42 CEST 2008
 */
package java.awt;

public interface LayoutManager2 extends java.awt.LayoutManager
{

   public void addLayoutComponent(java.awt.Component arg0, java.lang.Object arg1);
   public java.awt.Dimension maximumLayoutSize(java.awt.Container arg0);
   public float getLayoutAlignmentX(java.awt.Container arg0);
   public float getLayoutAlignmentY(java.awt.Container arg0);
   public void invalidateLayout(java.awt.Container arg0);
}
