// This file is part of KeY - Integrated Deductive Software Design 
//
// Copyright (C) 2001-2011 Universitaet Karlsruhe (TH), Germany 
//                         Universitaet Koblenz-Landau, Germany
//                         Chalmers University of Technology, Sweden
// Copyright (C) 2011-2013 Karlsruhe Institute of Technology, Germany 
//                         Technical University Darmstadt, Germany
//                         Chalmers University of Technology, Sweden
//
// The KeY system is protected by the GNU General 
// Public License. See LICENSE.TXT for details.
// 

/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed May 14 11:55:34 CEST 2008
 */
package javax.swing;

public interface ScrollPaneConstants
{
   public final static java.lang.String VIEWPORT = "VIEWPORT";
   public final static java.lang.String VERTICAL_SCROLLBAR = "VERTICAL_SCROLLBAR";
   public final static java.lang.String HORIZONTAL_SCROLLBAR = "HORIZONTAL_SCROLLBAR";
   public final static java.lang.String ROW_HEADER = "ROW_HEADER";
   public final static java.lang.String COLUMN_HEADER = "COLUMN_HEADER";
   public final static java.lang.String LOWER_LEFT_CORNER = "LOWER_LEFT_CORNER";
   public final static java.lang.String LOWER_RIGHT_CORNER = "LOWER_RIGHT_CORNER";
   public final static java.lang.String UPPER_LEFT_CORNER = "UPPER_LEFT_CORNER";
   public final static java.lang.String UPPER_RIGHT_CORNER = "UPPER_RIGHT_CORNER";
   public final static java.lang.String LOWER_LEADING_CORNER = "LOWER_LEADING_CORNER";
   public final static java.lang.String LOWER_TRAILING_CORNER = "LOWER_TRAILING_CORNER";
   public final static java.lang.String UPPER_LEADING_CORNER = "UPPER_LEADING_CORNER";
   public final static java.lang.String UPPER_TRAILING_CORNER = "UPPER_TRAILING_CORNER";
   public final static java.lang.String VERTICAL_SCROLLBAR_POLICY = "VERTICAL_SCROLLBAR_POLICY";
   public final static java.lang.String HORIZONTAL_SCROLLBAR_POLICY = "HORIZONTAL_SCROLLBAR_POLICY";
   public final static int VERTICAL_SCROLLBAR_AS_NEEDED = 20;
   public final static int VERTICAL_SCROLLBAR_NEVER = 21;
   public final static int VERTICAL_SCROLLBAR_ALWAYS = 22;
   public final static int HORIZONTAL_SCROLLBAR_AS_NEEDED = 30;
   public final static int HORIZONTAL_SCROLLBAR_NEVER = 31;
   public final static int HORIZONTAL_SCROLLBAR_ALWAYS = 32;

}
