name: Tests

on:
  # Trigger the workflow on push to master (ignoring .md only changes)
  push:
    branches:
      - master
      - devel
    paths-ignore:
      - '**.md'

  # Trigger the workflow on any pull_request (ignoring .md only changes)
  pull_request:
    paths-ignore:
      - '**.md'
      - doc
      - dev-files

  # Enable manual triggering (important for contributors to enable a check on their fork)
  workflow_dispatch:

# If a build is running in the current branch, and the branch is updated, we cancel the previous build and start
# a new one with the updated changes.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  gradle_test_on_merge:
    strategy:
      ## Optionally cancel all other combinations if one fails
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ] #, macos-latest, windows-latest ]
        jdk: [ 21 ]

    env:
      OS: ${{ matrix.os }}
      JDK: ${{ matrix.jdk }}

    runs-on: ${{ matrix.os }}

    steps:
      ## Checkout the current version of the code from the repo.
      - &checkout
        name: Checkout latest code
        uses: actions/checkout@v7
        with:
          fetch-depth: "0"

      ## Setup the specified version of Java (includes maven/gradle).
      - &setupjava
        name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'              # v2 requires explicitly stating the distribution - `zulu` and `adopt` supported at time of writing
          java-version: ${{ matrix.jdk }}   # Use matrix to select which JDK level to use
          java-package: jdk                 # optional (jdk or jre) - defaults to jdk
          cache: 'gradle'

      - &checkjava
        name: Echo exact java version being used
        run: java -version
      - &sonarcache
        name: Cache SonarCloud packages
        uses: actions/cache@v6
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - &gradletest
        name: Test with Gradle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew --continue --parallel test

      - &report
        name: Test reporting
        uses: dorny/test-reporter@v3
        if: success() || failure()
        with:
          name: Test Report
          path: "**/build/test-results/tests/test/**/*.xml"
          reporter: java-junit

  gradle_test_on_branch:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ] #, macos-latest, windows-latest ]
        jdk: [ 21 ]

    env:
      OS: ${{ matrix.os }}
      JDK: ${{ matrix.jdk }}

    runs-on: ${{ matrix.os }}

    steps:
      - &checkout
        name: Checkout latest code
        uses: actions/checkout@v7
        with:
          fetch-depth: "0"
          ref: ${{github.event.pull_request.head.sha}}
      - *setupjava
      - *checkjava
      - *sonarcache
      - *gradletest
      - *report
