/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    testImplementation(project(":jmlparser-core"))
    testImplementation(project(":jmlparser-symbol-solver-core"))
    testImplementation(project(":jmlparser-core-testing"))
    testImplementation(project(":jmlparser-core-testing-bdd"))
    testImplementation(project(":jmlparser-symbol-solver-testing"))
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.params)
    testImplementation(libs.org.hamcrest.hamcrest.library)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.com.squareup.okhttp3.okhttp)
    testImplementation(libs.org.mockito.mockito.inline)
}

description = "io.github.jmltoolkit:jmlparser-jml-tests"
